INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'You didn''t make the minimum score to get to the next level.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Keep trying, one day you shall succeed.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Ur suck! Even my grandma can beat that.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'All people have the right to be stupid.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Are you trying to be the biggest loser?');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'That''s easy, even I can do that!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'One fail toward forward succeed.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'What''s it like to lose so badly?');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'How about best two out of three?');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'No way, you can do better than that...');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Winner never quit, quitters never win.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Opps!!! U need to do better than that.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Tick tock, opps... you lose again.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Access denied--nah nah na nah nah!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'You love to be a loser, don''t you?');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'I know ur a smartie. So, prove it!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Stop being a loser. It is my turn.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'You suck! My grandma can beat that!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Cheer up! The worst is yet to come.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Comon! You can do better than that.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Badabing Badabang Badaboom! sucker!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'To be OLD and WISE, you must first have to be YOUNG and STUPID.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'You gotta try your best now. Else, Ima kick your butt.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Yea Ur a loser.. but Ur the worst loser I''ve never met!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'You know you aint a loser. Try again!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'You aint the only loser in the house.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'You know you are smart. So, prove it!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'it is what it is [ unless it is not ]');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'You know what make a good loser? Practice.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'I can see clearly now, your brain is dead.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'If you can accept losing, you can''t win. Try again, will you?');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'OPsS!!! You lose again!!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Muahahaha! U lost again.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Ohhh! That''s gotta hurt.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Who wanna be on TOP? Keep trying!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'All the world loves a good loser.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Never run away from your problem.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Don''t say a word. Just do it!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Doing no wrong makes a right.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Winner vs. Loser, choose one.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Nutsy Cuckoo!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Oh god! Please help this sucker win.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Try again. Lose again. Let''s dance! ');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'You can do better. Try again please!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Say you love me. I gain you a wish!.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Winners are not those who never fail, but those who never quit');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Congratz! You won the title world''s greatest loser.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'GIVE UP is a real loser. Don''t tell me You are one.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'No one is perfect, that''s why pencils have erasers.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'You didn''t lose the game. You just run out of time.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'One short loser boy.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'This too shall pass!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Success doesn''t come to you? you come to it. ');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'It''s ok!!! Don''t cry. I won''t tell your mama.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Artificial Intelligence is no match for Natural Stupidity.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Congratulation! You now won the title "the biggest loser".');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'There''s nothing wrong with being a loser, right? ');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Not this time. Maybe next time. Try again please!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Human do make mistake.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Common! Try your best!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Wah-ha-ha-ha-howwww...');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Don''t worry! Be happy!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Mistakes are stepping stones to success.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'You never a loser until you quit trying.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'It''s a good loser who finally loses out.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'That was easy! But too bad….');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'OMG!!! Ur suck! Unbelievable');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'The loser is always at fault');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'The sooner you fall behind. The more time you''ll have to catch up.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'it is always advisable to be a loser if you cannot become a winner');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'When I lose a match, I know that I lose on the court but not life.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Ooh-ooh-ooooh!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Never give up!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Don''t be sad. Let''s dance!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Sucker! Sucker! Suuuckerr!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'I shall let you know that You are qualify for The Loser Club. Join Now!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'There is a crack in everything. That''s how the light get in.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Today lost. Tomorrow lost. Don''t worry. Next life you shall win so keep trying.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'The only failure is when you say, I''d give up.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'You will make it!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'No No No No NO!!!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Life is a gamble.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'When the world says ''give up'' hope whispers I try one more time.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,' "Beg for mercy and maybe I''ll let you win"');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Once you learn to quit, it becomes a habit.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Oh man! That was hilarious. Its suck for you though.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'There''s such a thin line between winning and losing.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'TOO BAD! SO SAD!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Well play old man.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'first rule is not to lose. The second rule is not to forget the first rule.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'I won?!. O my gosh- I never win! You must suck!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Do me a favor. Wake me when you''re done losing.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Show me a good loser, I will show you an idiot.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Seriously! Are you even trying?');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Second is just the first loser.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'You lost because you told yourself you lost.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Not this life. Maybe next life. Keep trying!');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'You were not born a winner, and you were not born a loser. You are what you make yourself to be.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Without loser, where would the winner be?');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Losing doesn''t eat you the way it used to. You just get ready for the next play, the next game, the next season.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'I like bad loser, all good loser lose too often.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Losing is no disgrace if you''ve given your best.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Lose an hour in the morning, you will spend all day looking for it.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Wise men never sit and wail their loss, but cheerily seek how to redress their harms.');
INSERT INTO Messages (Id,TypeId,Message) VALUES (NULL,3,'Caution! Loser is in the town.');
